EndToEnd/Models/Company.cs
using System;

namespace EndToEnd.Models
{
    public class Company
    {
        public int CompanyId { get; set; }


        public string Name { get; set; }

        public string Slogan { get; set; }

        public DateTime DateCreated { get; set; }
    }
}

EndToEnd/Models/SmsUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace EndToEnd.Models
{
    public class SmsUser : Person
    {
        public string SmsUserId { get; set; }

        public string DesiredNameForSms { get; set; }

        public bool? IsBusiness { get; set; }
        public string BusinessName { get; set; }
        public bool? IsIndividual { get; set; }
        public string Slogan { get; set; }
        public bool Active { get; set; } = true;

        public bool Activated { get; set; } = false;

        // nav links

        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<StaffLogin> StaffLogins { get; set; }

        public  virtual  ICollection<SmsTransaction> SmsTransactions { get; set; }

    }


}

EndToEnd/Models/Staff.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;

namespace EndToEnd.Models
{
    public class Staff : Person
    {
        public string StaffId { get; set; }
        public string BankCode { get; set; }
        public string StaffCode { get; set; }
        public string Level { get; set; }
        public DropDown.UserGroupList UserGroupList  { get; set; }

       // public UserGroup UserGroup { get; set; }

        public int AuthId { get; set; }
        public virtual Authentication Authentication { get; set; }

        public int CompanyId { get; set; }
        public virtual Company Company { get; set; }


        public int UserTypeId { get; set; }
        public int SmsPurchaseTransactionId { get; set; }
        public int StatusId { get; set; }
        public bool Active { get; set; }
    }
}

EndToEnd/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EndToEnd.Models;

namespace EndToEnd.Controllers
{
    public class CompaniesController : BaseController
    {
        //private FinCoreDB db = new FinCoreDB();

        // GET: Companies
        public async Task<ActionResult> Index()
        {
            return View(await db.Companies.ToListAsync());
        }

        // GET: Companies/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = await db.Companies.FindAsync(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create( Company company)
        {
            if (ModelState.IsValid)
            {
                db.Companies.Add(company);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(company);
        }

        // GET: Companies/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = await db.Companies.FindAsync(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit( Company company)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = await db.Companies.FindAsync(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Company company = await db.Companies.FindAsync(id);
            db.Companies.Remove(company);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

       
    }
}

EndToEnd/Controllers/SmsUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using EndToEnd.Models;
using Microsoft.AspNet.Identity;
using PagedList;

namespace EndToEnd.Controllers
{
    [Authorize]
    public class SmsUsersController : BaseController
    {
        //  private FinCoreDB db = new FinCoreDB();

        // GET: SmsUsers
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Index()
        {
            return View(await db.SmsUsers.ToListAsync());
        }

        // GET: SmsUsers/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SmsUser smsUser = await db.SmsUsers.FindAsync(id);
            if (smsUser == null)
            {
                return HttpNotFound();
            }
            return View(smsUser);
        }

        // GET: SmsUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SmsUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(SmsUser smsUser)        {
            if (ModelState.IsValid)
            {
                smsUser.State = smsUser.StateList.ToString();
                smsUser.Gender = smsUser.GenderList.ToString();

                db.SmsUsers.Add(smsUser);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(smsUser);
        }

        // GET: SmsUsers/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SmsUser smsUser = await db.SmsUsers.FindAsync(id);
            if (smsUser == null)
            {
                return HttpNotFound();
            }
            return View(smsUser);
        }

        // POST: SmsUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit( SmsUser smsUser)
        {
            if (ModelState.IsValid)
            {
                smsUser.State = smsUser.StateList.ToString();
                smsUser.Gender = smsUser.GenderList.ToString();

                db.Entry(smsUser).State = EntityState.Modified;
                await db.SaveChangesAsync();

                ViewBag.Message = "Profile data successfully edited and saved";
                return View();
            }
            return View(smsUser);
        }

        // GET: SmsUsers/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SmsUser smsUser = await db.SmsUsers.FindAsync(id);
            if (smsUser == null)
            {
                return HttpNotFound();
            }
            return View(smsUser);
        }

        // POST: SmsUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            SmsUser smsUser = await db.SmsUsers.FindAsync(id);
            db.SmsUsers.Remove(smsUser);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult DeativateList()
        {
             return View(db.SmsUsers.Where(s => s.Active == false).ToList());

        }

        public ActionResult Deativate(string id)
        {
            if (id == null)
            {
                id = User.Identity.GetUserId();
            }
            SmsUser smsUser = db.SmsUsers.Find(id);
            if (smsUser == null)
            {
                return HttpNotFound();
            }
            return View(smsUser);
        }
        [HttpPost]
        public async Task<ActionResult> Deativate(SmsUser smsUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(smsUser).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(smsUser);
        }

        [HttpGet]
        public async Task<ActionResult> ActivateList(string message)
        {
            ViewBag.Message = message;
            return View(await db.SmsUsers.Where(s => s.Activated == false).ToListAsync());

        }

       
        public async void ActivateAction()
        {
              var  id = User.Identity.GetUserId();

            SmsUser smsUser = db.SmsUsers.Find(id);
            if (smsUser == null)
            {
                RedirectToAction ("ActivateList", new {message = "Activation not successful, try again"});
            }
            smsUser.Activated = true;

            db.Entry(smsUser).State = EntityState.Modified;
            await db.SaveChangesAsync();
            RedirectToAction ("ActivateList", new {message = "Activation was successful"});

        }

        //[HttpPost]
        //public async Task<ActionResult> Activate(SmsUser smsUser)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(smsUser).State = EntityState.Modified;
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("Index");
        //    }
        //    return View(smsUser);
        //}

    }
}

EndToEnd/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EndToEnd.Models;

namespace EndToEnd.Controllers
{
    [Authorize]
    public class StaffsController : BaseController
    {
       // private FinCoreDB db = new FinCoreDB();

        // GET: Staffs
        public async Task<ActionResult> Index()
        {
            return View(await db.Staffs.ToListAsync());
        }

        // GET: Staffs/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = await db.Staffs.FindAsync(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // GET: Staffs/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Staffs.Add(staff);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(staff);
        }

        // GET: Staffs/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = await db.Staffs.FindAsync(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staff).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = await db.Staffs.FindAsync(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Staff staff = await db.Staffs.FindAsync(id);
            db.Staffs.Remove(staff);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EndToEnd/Views/Shared/Partials/_Admin.cshtml
@using Microsoft.AspNet.Identity

<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="~/Theme/dist/img/user.svg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>@User.Identity.GetUserName()</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            <li id="left-sidebar-menu-dashboard" class="treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Subscribers</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li id="left-sidebar-menu-dashboard-dashboardV1"><a href="@Url.Action("Index", "SmsUsers")"><i class="fa fa-circle-o"></i> View Subscribers</a></li>
                    <li id="left-sidebar-menu-dashboard-dashboardV2"><a href="@Url.Action("Create", "SmsUsers")"><i class="fa fa-circle-o"></i> Create Subscribers</a></li>
                    @*<li id="left-sidebar-menu-dashboard-dashboardV3"><a href="@Url.Action("Delete", "SmsUsers")"><i class="fa fa-circle-o"></i> Delete Subscriber</a></li>*@
                    <li id="left-sidebar-menu-dashboard-dashboardV5"><a href="@Url.Action("DeativateList", "SmsUsers")"><i class="fa fa-circle-o"></i> Deactivate Subscriber</a></li>
                    <li id="left-sidebar-menu-dashboard-dashboardV6"><a href="@Url.Action("ActivateList", "SmsUsers")"><i class="fa fa-circle-o"></i> Activate Subscriber</a></li>

                </ul>
            </li>
            <li id="left-sidebar-menu-charts" class="treeview">
                <a href="#">
                    <i class="fa fa-pie-chart"></i>
                    <span>Sms Actions</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li id="left-sidebar-menu-charts-chartjs"><a href="@Url.Action("Create", "CreateChargeRates")"><i class="fa fa-circle-o"></i> Create Charge Rate</a></li>
                    <li id="left-sidebar-menu-charts-chartjs"><a href="@Url.Action("Create", "SmsUnits")"><i class="fa fa-circle-o"></i> Create SmsUnit</a></li>

                    <li id="left-sidebar-menu-charts-chartjs"><a href="@Url.Action("Create", "SendSms")"><i class="fa fa-circle-o"></i> Send SmsToSingle</a></li>
                    <li id="left-sidebar-menu-charts-morris"><a href="@Url.Action("#", "Charts")" class="disable_href"><i class="fa fa-circle-o"></i> Send SmsToMany</a></li>
                    <li id="left-sidebar-menu-charts-flot"><a href="@Url.Action("Flot", "Charts")" class="disable_href"><i class="fa fa-circle-o"></i> Send ToExcel List</a></li>

                </ul>
            </li>
            <li id="left-sidebar-menu-widgets">
                <a href="#" class="disable_href">
                    <i class="fa fa-th"></i> <span>Email Actions</span>
                    <small class="label pull-right bg-green">Coming Soon</small>
                </a>
                <ul class="treeview-menu">
                    <li id="left-sidebar-menu-charts-chartj"><a href="#"><i class="fa fa-circle-o"></i> Send EmailToSingle</a></li>
                    <li id="left-sidebar-menu-charts-morri"><a href="#"><i class="fa fa-circle-o"></i> Send EmailToMany</a></li>
                    <li id="left-sidebar-menu-charts-flots"><a href="#"><i class="fa fa-circle-o"></i> <small class="label pull-right bg-green">Coming Soon</small>
                Send Email ToExcel-List</a> </li>
                </ul>
            </li>

            <li id="left-sidebar-menu-elements" class="treeview">
                <a href="#" class="disable_href">
                    <i class="fa fa-laptop"></i>
                    <span>Support </span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li id="left-sidebar-menu-elements-general"><a href="@Url.Action("General", "Elements")" ><i class="fa fa-circle-o"></i> View Support Tickets</a></li>
                    <li id="left-sidebar-menu-elements-icons"><a href="@Url.Action("Icons", "Elements")"><i class="fa fa-circle-o"></i> Respond To Tickets</a></li>
               </ul>
            </li>
            <li id="left-sidebar-menu-forms" class="treeview">
                <a href="#">
                    <i class="fa fa-edit"></i> <span>Accountability</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <!--Note  to include sorting in all 3 controller actions -->
                    <li id="left-sidebar-menu-forms-general"><a href="@Url.Action("Index", "PurchaseSms")"><i class="fa fa-circle-o"></i> All Token Purchase</a></li>
                    <li id="left-sidebar-menu-forms-advanced"><a href="@Url.Action("Index", "Purchases")"><i class="fa fa-circle-o"></i>View Payments </a></li>
                    <li id="left-sidebar-menu-forms-editors"><a href="@Url.Action("Index", "SmsPurchaseTransactions")"><i class="fa fa-circle-o"></i>  All Token Transactions</a></li>

                </ul>
            </li>
            <li id="left-sidebar-menu-tables" class="treeview">
                <a href="#" class="disable_href">
                    <i class="fa fa-table"></i> <span>Payment</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li id="left-sidebar-menu-tables-simple"><a href="@Url.Action("Index", "Payments")"><i class="fa fa-circle-o"></i> Payment Approval</a></li>
                    <li id="left-sidebar-menu-tables-data"><a href="@Url.Action("Delete", "Tables")"><i class="fa fa-circle-o"></i> Cancel Purchase</a></li>
                </ul>
            </li>


            <li id="left-sidebar-menu-examples" class="treeview">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Staffs</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li id="left-sidebar-menu-examples-invoice"><a href="@Url.Action("Index", "Staffs")"><i class="fa fa-circle-o"></i> View Staffs</a></li>
                    <li id="left-sidebar-menu-examples-profileex"><a href="@Url.Action("Create", "Staffs")"><i class="fa fa-circle-o"></i> Add Staff</a></li>
                    <li id="left-sidebar-menu-examples-login"><a class="disable_href" href="@Url.Action("Deactivate", "Staffs")"><i class="fa fa-circle-o"></i> Deactivate Staff</a></li>
                   <li id="left-sidebar-menu-examples-register"><a class="disable_href" href="@Url.Action("Activate", "Staffs")"><i class="fa fa-circle-o"></i> Activate Staff</a></li>
                    @*<li id="left-sidebar-menu-examples-lockscreen"><a href="@Url.Action("Lockscreen", "Examples")"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
                    <li id="left-sidebar-menu-examples-p404"><a href="@Url.Action("P404", "Examples")"><i class="fa fa-circle-o"></i> 404 Error</a></li>
                    <li id="left-sidebar-menu-examples-p500"><a href="@Url.Action("P500", "Examples")"><i class="fa fa-circle-o"></i> 500 Error</a></li>
                    <li id="left-sidebar-menu-examples-blank"><a href="@Url.Action("Blank", "Examples")"><i class="fa fa-circle-o"></i> Blank Page</a></li>
                    <li id="left-sidebar-menu-examples-pace"><a href="@Url.Action("Pace", "Examples")"><i class="fa fa-circle-o"></i> Pace Page</a></li>*@
                </ul>
            </li>

            <li id="left-sidebar-menu-documentation">
                <a class="disable_href" href="@Url.Action("Index", "Documentation")">
                    <i class="fa fa-book"></i>
                    <span>User Usage Guide</span>
                </a>
            </li>
            @*<li class="header">LABELS</li>
            <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>*@
        </ul>
    </section>
</aside>
<link href="~/Content/Site.css" rel="stylesheet" />

EndToEnd/Views/Shared/Partials/_FooterPartial.cshtml
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.3.2
    </div>
    <strong>Copyrights | FinCore Messaging (FINMSG) |  &copy; @DateTime.Now.Year <a href="#">Silicon Gates Software</a>.</strong> All rights
    reserved.
</footer>